name: Helm Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: helloworlde/helm-chart@master
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
